# Generated by Django 6.0.4 on 2026-04-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('model_designation', models.CharField(blank=True, help_text='E.g. F-16C Block 50, MiG-29A, etc.', max_length=32, verbose_name='Model Designation')),
                ('nickname', models.CharField(blank=True, help_text="E.g. 'Viper' for F-16, 'Fulcrum' for MiG-29, etc.", max_length=32, verbose_name='Nickname')),
                ('country', models.CharField(choices=[('US', 'United States'), ('RU', 'Russia / USSR'), ('UK', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('SE', 'Sweden'), ('CN', 'China'), ('JP', 'Japan'), ('ES', 'Spain'), ('BR', 'Brazil'), ('IN', 'India'), ('CA', 'Canada'), ('IL', 'Israel'), ('TR', 'Turkey'), ('MN', 'Multinational')], max_length=2, verbose_name='Country of Origin')),
                ('era', models.CharField(choices=[('WW2', 'World War II'), ('CW', 'Cold War'), ('MO', 'Modern')], max_length=3, verbose_name='Era')),
                ('fidelity_level', models.CharField(choices=[('FF', 'Full Fidelity (Clickable)'), ('FC', 'Flaming Cliffs (Simplified)'), ('MD', 'Community Mod')], max_length=2, verbose_name='Fidelity Level')),
                ('flight_model', models.CharField(blank=True, help_text="E.g. 'Standard', 'Advanced', 'Realistic', etc.", max_length=32, verbose_name='Flight Model')),
                ('is_flayable', models.BooleanField(default=True, help_text='Indicates if the aircraft is currently flyable in DCS World.', verbose_name='Is Flyable')),
                ('carrier_capable', models.BooleanField(default=False, help_text='Indicates if the aircraft can operate from aircraft carriers.', verbose_name='Carrier Capable')),
                ('max_speed', models.CharField(blank=True, help_text="E.g. 'Mach 2.0', '1500 km/h', etc.", max_length=32, verbose_name='Max Speed')),
                ('service_ceiling', models.CharField(blank=True, help_text="E.g. '50,000 ft', '15,000 m', etc.", max_length=32, verbose_name='Service Ceiling')),
                ('range', models.CharField(blank=True, help_text="E.g. '1,500 km', '800 nmi', etc.", max_length=32, verbose_name='Range')),
                ('thrust_to_weight', models.CharField(blank=True, help_text="E.g. '1.2', '0.9', etc.", max_length=32, verbose_name='Thrust-to-Weight Ratio')),
                ('engine', models.CharField(blank=True, help_text="E.g. 'Pratt & Whitney F100-PW-229', 'Saturn AL-31F', etc.", max_length=64, verbose_name='Engine Type')),
                ('engine_count', models.IntegerField(blank=True, help_text='Number of engines (e.g. 1, 2, etc.)', null=True, verbose_name='Engine Count')),
                ('has_ejector_seat', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with an ejector seat.', verbose_name='Has Ejector Seat')),
                ('has_radar', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with a radar system.', verbose_name='Has Radar')),
                ('radar', models.CharField(blank=True, help_text="E.g. 'AN/APG-68', 'N001 VEP', etc.", max_length=64, verbose_name='Radar System')),
                ('has_rwr', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with a Radar Warning Receiver.', verbose_name='Has RWR')),
                ('rwr', models.CharField(blank=True, help_text="E.g. 'AN/ALR-56M', 'SPO-15', etc.", max_length=64, verbose_name='RWR System')),
                ('has_ecm', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with Electronic Countermeasures.', verbose_name='Has ECM')),
                ('ecm', models.CharField(blank=True, help_text="E.g. 'AN/ALQ-131', 'Khibiny', etc.", max_length=64, verbose_name='ECM System')),
                ('has_datalink', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with a datalink system.', verbose_name='Has Datalink')),
                ('air_to_air', models.BooleanField(default=False, help_text='Indicates if the aircraft is capable of engaging in air-to-air combat.', verbose_name='Air-to-Air Capability')),
                ('air_to_ground', models.BooleanField(default=False, help_text='Indicates if the aircraft is capable of engaging in air-to-ground combat.', verbose_name='Air-to-Ground Capability')),
                ('air_to_sea', models.BooleanField(default=False, help_text='Indicates if the aircraft is capable of engaging in air-to-sea combat.', verbose_name='Air-to-Sea Capability')),
                ('reconnaissance', models.BooleanField(default=False, help_text='Indicates if the aircraft is capable of performing reconnaissance missions.', verbose_name='Reconnaissance Capability')),
                ('internal_canon', models.BooleanField(default=False, help_text='Indicates if the aircraft is equipped with an internal cannon.', verbose_name='Internal Cannon')),
                ('hardpoint_count', models.IntegerField(blank=True, help_text='Number of hardpoints available for weapons and equipment.', null=True, verbose_name='Hardpoint Count')),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the aircraft.', verbose_name='Image URL')),
                ('dcs_wiki_url', models.URLField(blank=True, help_text="URL to the aircraft's page on the hoggit Wiki.", verbose_name='DCS Wiki URL')),
                ('chucks_guide_url', models.URLField(blank=True, help_text="URL to the aircraft's page on Chuck's Guide.", verbose_name="Chuck's Guide URL")),
                ('offcial_manual_url', models.URLField(blank=True, help_text='URL to the official manual or documentation for the aircraft.', verbose_name='Official Manual URL')),
                ('tutorial_video_url', models.URLField(blank=True, help_text='URL to a tutorial video for the aircraft.', verbose_name='Tutorial Video URL')),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('website', models.URLField(blank=True, verbose_name='Official Website')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='ManuFacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('website', models.URLField(blank=True, verbose_name='Official Website')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g. FI, AT, MR, HE, TR, SP', max_length=5, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AircraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aircraft/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aircrafttype')),
            ],
            options={
                'verbose_name': 'Aircraft Image',
                'verbose_name_plural': 'Aircraft Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AircraftVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Video URL')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='Title')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.aircrafttype')),
            ],
            options={
                'verbose_name': 'Aircraft Video',
                'verbose_name_plural': 'Aircraft Videos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='module_developers',
            field=models.ManyToManyField(related_name='aircraft_types', to='core.developer', verbose_name='Developers'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_types', to='core.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='roles',
            field=models.ManyToManyField(help_text='E.g. FI, AT, MR, HE, TR, SP', related_name='aircraft_types', to='core.role', verbose_name='Roles'),
        ),
    ]
