# Generated by Django 6.0.4 on 2026-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='climb_rate',
            field=models.CharField(blank=True, help_text="E.g. '50,000 ft/min', '250 m/s', etc.", max_length=32, verbose_name='Climb Rate'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='crew',
            field=models.IntegerField(blank=True, help_text='Number of crew members (e.g. 1 for single-seat, 2 for tandem, etc.)', null=True, verbose_name='Crew'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='empty_weight',
            field=models.CharField(blank=True, help_text="E.g. '10,000 kg', '22,000 lbs', etc.", max_length=32, verbose_name='Empty Weight'),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='max_takeoff_weight',
            field=models.CharField(blank=True, help_text="E.g. '20,000 kg', '44,000 lbs', etc.", max_length=32, verbose_name='Max Takeoff Weight'),
        ),
    ]
